export default () => ({
    loading_jobs: true,
    modal_shield: false,
    // LOCUM
    locum_allocated_jobs: [],
    locum_allocated_jobs_count: 0,
    locum_available_jobs: [],
    locum_available_jobs_count: 0,
    locum_matched_jobs: [],
    locum_matched_jobs_count: 0,
    locum_applied_jobs: [],
    locum_applied_jobs_count: 0,
    locum_unsuccessful_jobs: [],
    locum_unsuccessful_jobs_count: 0,
    locum_declined_jobs: [],
    locum_declined_jobs_count: 0,
    locum_cancelled_jobs: [],
    locum_cancelled_jobs_count: 0,
    locum_completed_jobs: [],
    locum_completed_jobs_count: 0,
    locum_private_jobs: [],
    locum_unavailabilities: [],
    locum_unavailabilities_count: 0,
})