export default () => ({
    // register practice
    search_results: [],
    practice_details: {
        surgery_id: '',
        name: '',
        phone_number: '',
        code: '',
        clinical_commissioning_group_name: '',
        address_line_1: '',
        address_line_2: '',
        address_line_3: '',
        address_line_4: '',
        address_line_5: '',
        postcode: '',
        coordinate_x: '',
        coordinate_y: '',
    },
    practice_surgery_details: {
        name: '',
        phone_number: '',
        code: '',
        clinical_commissioning_group_name: '',
        address_line_1: '',
        address_line_2: '',
        address_line_3: '',
        address_line_4: '',
        address_line_5: '',
        postcode: '',
        coordinate_x: '',
        coordinate_y: '',
    },
    practice_account_details: {
        hub_practice_id: null,
        surgeries: [],
        type: '',
        hub_type: '',
        title: '',
        first_name: '',
        last_name: '',
        suffix: '',
        practice_role: '',
        practice_type_id: [],
        email: '',
        password: '',
        password_confirmation: '',
        referral_code: null,
        national_insurance_number: null,
        sd_number: null,
        paying_reference: null,
        ea_code: null,
        professional_nhs_expenses: null,
        section_scheme_year: null,
        added_year_contributions: null,
        added_early_retirement_contributions: null,
        nhsps_employer_contributions: null,
        nhs_pension_scheme_employing_authority_name: null,
    },
    practice_detail_form_error: [],
    practice_surgery_detail_form_error: [],
    practice_account_detail_form_error: [],
    //  register locum
    activeComponent: 'LocumStage1',
    professions: [],
    gp_qualifications: [],
    others_qualifications: [],
    clinical_systems: [],
    spoken_languages: [],
    practice_types: [],
    mandatory_trainings: [],
    account_details: {
        title: '',
        first_name: '',
        last_name: '',
        suffix: '',
        gender: '',
        date_of_birth: null,
        mobile_number: '',
        home_number: '',
        work_number: ''
    },
    address_details: {
        post_code: '',
        address_line_1: '',
        address_line_2: '',
        address_line_3: ''
    },
    professional_details: {
        view_locum_jobs: false,
        view_permanent_jobs: false,
        reference_locum_compliance_documents: [],
        // gmc_or_nmc_number: '',
        // mpl_or_npl_number: '',
        nhs_smart_card_id_number: '',
        profession_id: '',
        qualification_id: [],
        clinical_system_id: [],
        spoken_language_id: [],
        min_rate_per_hour: 0,
        max_rate_per_hour: 0,
        min_rate_per_half_day_session: 0,
        max_rate_per_half_day_session: 0,
        min_rate_per_whole_day_session: 0,
        max_rate_per_whole_day_session: 0,
        practice_type_id: [],
        mandatory_training_id: [],
        profession_category_id: ''
    },
    payroll_details: {
        employment_type: "Self-Employed",
        company_registration_number: "",
        utr_number: "",
        paid_under_payroll: false,
        payroll_account_name: "",
        payroll_bank_name: "",
        payroll_sort_code: "",
        payroll_account_number: "",
        account_name: "",
        bank_name: "",
        sort_code: "",
        account_number: "",
        ir35: false,
        claim_nhs: false,
        nhs_number: "",
    },
    credential_details: {
        email: '',
        password: '',
        password_confirmation: '',
        referral_code: null
    },
    account_detail_form_error: [],
    address_detail_form_error: [],
    professional_detail_form_error: [],
    payroll_detail_form_error: [],
    credential_detail_form_error: [],
    register_loading: false,
    stage_1_details_form_error: [],
    stage_2_pt_1_details_form_error: [],
    stage_2_pt_2_details_form_error: [],
    stage_1_details: {
        view_locum_jobs: false,
        view_permanent_jobs: false,
        profession_id: "",
        title: "",
        first_name: "",
        last_name: '',
        suffix: '',
        mobile_number: '',
        email: '',
        password: '',
        password_confirmation: ''
    },
    stage_2_pt_1_details: {
        reference_locum_compliance_documents: [],
        nhs_smart_card_id_number: "",
        post_code: null,
        address_line_1: "",
        address_line_2: "",
        address_line_3: ""
    },
    stage_2_pt_2_details: {
        privacy_policy: false,
        referral_code: null,
        mandatory_locum_compliance_documents: [],
        files: []
    },
    mandatory_compliance_documents: [],
    signup_loading: false
})